version: '3'
services:
  server:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    environment:
      USE_TEST_AUTH: ${USE_TEST_AUTH}
    expose:
      - ${APP_SERVER_PORT}
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      USE_TEST_AUTH: ${USE_TEST_AUTH}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
