sudo: required

dist: trusty
language: node_js
node_js:
  - "10.3.0"

services:
  - docker

before_install:
  - npm install -g npm@6.4.1
  - docker pull node:10.13-alpine
  - docker pull nginx:alpine

install:
  - cd client && npm install && cd ..
  - cd server && npm install && cd ..

script:
  # Lint server and client
  - npm --prefix client run lint:ci
  - npm --prefix server run lint:ci

  # Build client development and production
  - npm --prefix client run build:dev
  - npm --prefix client run build

  # Test local development
  - APP_SERVER_PORT=9001 bash misc/test-server.sh

  # Test development Docker
  - pushd docker/development; docker-compose up -d; popd
  - APP_SERVER_PORT=8080 bash misc/test-server.sh
  - pushd docker/development; docker-compose down; popd

  # Test production Docker
  - pushd docker/production; docker-compose up -d; popd
  - APP_SERVER_PORT=8080 bash misc/test-server.sh
  - pushd docker/production; docker-compose down; popd

