sudo: required

dist: trusty
language: node_js
node_js:
  - "10.3.0"

services:
  - docker

before_install:
  - npm install -g npm@6.4.1
  - docker pull node:10.13-alpine
  - docker pull nginx:alpine

install:
  - cd client && npm install && cd ..
  - cd server && npm install && cd ..

script:
  - npm --prefix client run lint
  - npm --prefix client run lint:ci
  - npm --prefix client run build:dev
  - npm --prefix client run build
  - npm --prefix server run lint
  - npm --prefix server run lint:ci
  - npm --prefix server start &
  - npm --prefix server run test:api
  - pushd docker/development; docker-compose build; popd
  - pushd docker/production; docker-compose build; popd

