version: '3'
services:
  node-api:
    build:
      context: ../../
      dockerfile: docker/production/node-api/Dockerfile

  node-client:
    build:
      context: ../../client
      dockerfile: ../docker/production/node-client/Dockerfile
    volumes:
      - static-files:/app/build
  
  nginx:
    build: ./nginx
    links:
      - node-api
    ports:
      - ${APP_SERVER_PORT}:80
    volumes:
      - static-files:/app

volumes:
  static-files:
