version: '3'
services:
  api:
    build:
      context: ../../
      dockerfile: docker/production/api/Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      USE_TEST_DATA: ${USE_TEST_DATA}
    depends_on:
      - postgres

  nginx:
    build:
      context: ../../
      dockerfile: docker/production/nginx/Dockerfile
    ports:
      - ${LOCAL_PORT}:80
    depends_on:
      - api

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
