version: '3'
services:
  api:
    build:
      context: ../../
      dockerfile: docker/production/api/Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      USE_TEST_DATA: ${USE_TEST_DATA}
      USE_TEST_AUTH: ${USE_TEST_AUTH}
      APP_COOKIE_SECRET: ${APP_COOKIE_SECRET}
    depends_on:
      - postgres

  nginx:
    build:
      context: ../../
      dockerfile: docker/production/nginx/Dockerfile
    ports:
      - ${LOCAL_PORT}:80
    environment:
      APP_DOMAIN: $APP_DOMAIN
    depends_on:
      - api
      - proxy

  proxy:
    build:
      context: ../../
      dockerfile: docker/production/proxy/Dockerfile
    environment:
      FFGP_DB_DRIVER: postgres
      FFGP_DB_CONNECT: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=disable
      FFGP_INJECT_SCRIPT: ${APP_URL}/embed.js
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

